"""create users and notifications tables

Revision ID: 129f3fe8033a
Revises: 10b0287c9555
Create Date: 2025-11-02 20:05:30.487451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "129f3fe8033a"
down_revision: Union[str, Sequence[str], None] = "10b0287c9555"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("telegram_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("notification_attempts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_attempts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("notification_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "channel",
            postgresql.ENUM("EMAIL", "SMS", "TELEGRAM", name="notificationchannel"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("SUCCESS", "FAILED", name="attemptstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("attempt_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("notification_attempts_notification_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_attempts_pkey")),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
